### ISSUE TITLE
Question: Using ava, enzyme, React and JSDom and unable to unmount components

### ISSUE THREAD

**Issue by casparrolfe** [wallabyjs/ava-sample#1]
I've forked this repo (https://github.com/casparrolfe/ava-sample), I'm attempting to use AVA with JSDom and enzyme and I'm running into a few issues. I am able to mount components, but unable to unmount and I end up with this error.

`dangerouslyReplaceNodeWithMarkup(...): Cannot render markup in a worker thread. Make sure 'window' and 'document' are available globally before requiring React when unit testing or use ReactDOMServer.renderToString() for server rendering.`

This only occurs when using wallaby. Running AVA from the command line will result in all three tests passing.

Not sure what I'm missing!

**Comment by ArtemGovorov** [comment]
Thanks for the report! The bug was that the `setup` function was called after loading test files. The issue is fixed in core 1.0.274. It will be updated automatically in a few minutes, or you may [force the update in your editor](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
